name: CI

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: ESLint & Prettier
        run: |
          npm install eslint --save-dev
          npm run lint
          npx eslint --max-warnings=40 "src/**/*.js" "."
          npm run prettier
        
      - name: Build
        run: npm run build

      - name: Test and Coverage
        run: |
          npm install --save-dev nyc
          npx nyc npm test
          
      - name: Cypress Testing (e2e)
        run: |
          if [ -z "$(ls cypress/integration/*.spec.js)" ]; then
            echo "No Cypress test files found. Skipping Cypress tests.";
          else
            npm install cypress -D
            npx cypress open
          fi

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: SonarQube Scan
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=demo-project \
            -Dsonar.organization=demo-project \
            -Dsonar.host.url=http://52.28.63.193:9000 \
            -Dsonar.login=sqp_187666d3b257af45458411b3a6625c9f570f0622
